permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::463720542314:role/GlueJobsGithubActionRole
          role-duration-seconds: 900
          aws-region: us-east-1
      - name: Create modified_jobs.txt and synchronize jobs files
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep "jobs/" | awk -F '/' '{print $2}' | sort -u > ~/jobs_modified.txt
          readarray -t arr < ~/jobs_modified.txt
          if [ ${#arr[@]} -gt 0 ]; then
            echo "${#arr[@]} to update"
            for job in "${arr[@]}"
            do
              aws s3 sync "./jobs/${job}/" "s3://ladubief-glue-scripts/${job}" --region us-east-1
            done
            aws s3 cp ~/jobs_modified.txt s3://ladubief-glue-scripts/ --region us-east-1
          else
            echo "No job to update"
          fi
      - name: Cleanup
        run: |
          rm -rf ~/.aws
          rm -rf ~/jobs_modified.txt
